export const LOGIN_API = {
    ON_LOGGING_IN: 'on_logging_in',
    LOGIN_USER_SUCCESS: 'login_user_success',
    LOGIN_USER_FAIL: 'login_user_fail',
    RESET_LOGIN_RESPONSE: 'reset_login_response',
    RESET_OTP_RESPONSE: 'reset_otp_response',
    LOGOUT_ACTION_SUCCESS: 'logout_action_success',
    LOGOUT_ACTION_FAIL: 'logout_action_fail',
    START_LOADING: 'start_loading',
    STOP_LOADING: 'stop_loading',
    OTP_VERIFY: 'otp_verify',
    OTP_VERIFY_SUCCESS: 'otp_verify_success',
    GET_OTP_RESPONSE: 'get_otp_response',
    OTP_VERIFY_FAIL: 'otp_verify_fail',
    LOGOUT_ACTION: 'logout_action',
    INVALID_SESSION: 'invalid_session',
    MODIFY_TAKEAWAY_IMAGE_URL_SUCCESS: 'modify_takeaway_image_url_success',
    MODIFY_TAKEAWAY_DETAILS_IN_LIST: 'modify_takeaway_details_in_list',
    INVALID_SESSION_ACTION: 'invalid_session_action',
    PERSISTS_PHONE_NUMBER: 'persists_phone_number',
    GOOGLE_LOGIN_SUCCESS: 'google_login_success',
    GOOGLE_LOGIN_FAILURE: 'google_login_failure',
    SET_SELECTED_TAKEAWAY: 'set_selected_takeaway'
};
