export const DASHBOARD_TYPES = {
    APP_SYNC: 'APP_SYNC',
    CANCEL_REASON: { GET_CANCEL_REASON: 'GET_CANCEL_REASON' },
    DASHBOARD_API_CALLS: 'DASHBOARD_API_CALLS',
    GET_SETTINGS: 'GET_SETTINGS',
};
