export const LocalizationStrings = {
    WELCOME: 'Welcome',
    GENERATE_OTP: 'Generate OTP',
    LOGIN_SUCCESS: 'Login Successful',
    ADD_COUNTRY_CODE_FOR_REGISTERED_MOBILE_NUMBER: 'Enter your registered mobile number',
    USER_LOGIN_ERROR: 'This phone number is not associated with any account',
    INVALID_MOBILE_NUMBER: 'Invalid mobile number',
    SERVER_ERROR: 'Something went wrong. Please try again.',
    WENT_WRONG: 'Something went wrong',
    ACTIVATION_CODE: 'Activation Code: ',
    ACTIVATE: 'Activate',
    WIFI: 'WiFi',
    APPS: 'Apps',
    LOGIN_TEXT: 'Sign in to manage your takeaway',
    I_ACCEPT: 'I accept ',
    TERMS_AND_CONDITION: 'Terms & Conditions',
    AND: ' and ',
    PrivacyPolicy: 'Privacy Policy',
    FOR_ASSISTANCE: 'For assistance, scan QR code',
    SENT_OTP_TO: 'We have sent a ',
    DIGIT_OTP: ' digit OTP to',
    PLEASE_ENTER_A_VALID_OTP: 'Please enter a valid OTP',
    RESEND_SMS: 'Resend SMS',
    CALL_ME_INSTEAD: 'Call me instead',
};
