import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
    viewStyle: { flex: 1, justifyContent: 'center', paddingHorizontal: 20 },
    welcomeTextContainer: { marginBottom: 10, paddingHorizontal: 5 },
    welcomeTextStyle: { fontSize: 24, fontWeight: '700', color: '#1a1a1a' },
    phoneInputViewStyle: { height: 50 },
    flagStyle: { width: 30, height: 20 },
    phoneNumberTextStyle: { fontSize: 16, color: '#1a1a1a' },
    underLineViewStyle: { height: 1, marginTop: 4 },
    showErrorViewStyle: { backgroundColor: '#F44336' },
    showNormalViewStyle: { backgroundColor: '#e0e0e0' },
    errorInputViewStyle: { marginTop: 8 },
    registeredMobileNumberTextStyle: { fontSize: 12, color: '#888' },
    errorViewStyle: { marginTop: 8 },
    errorMessageTextStyle: { fontSize: 13, color: '#F44336' },
    inputViewStyle: { paddingTop: 20 },
    inputViewKeyboardAppStyle: { paddingTop: 10 },
    generateOTPViewStyle: { marginTop: 20 },
    generateOTPButtonCommonStyle: { borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
    generateOTPButtonEnableStyle: { backgroundColor: '#2d6a4f' },
    generateOTPButtonDisableStyle: { backgroundColor: '#aaa' },
    generateOTPTextStyle: { fontSize: 16, fontWeight: '600' },
    generateOTPTextEnableStyle: { color: '#fff' },
    generateOTPTextDisableStyle: { color: '#ddd' },
    spinnerContainer: { marginTop: 20, alignItems: 'center' },
    bubbleViewStyle: { marginTop: 12, alignItems: 'center' },
    activationView: { padding: 16, alignItems: 'center' },
    activationCodeText: { fontSize: 14, color: '#666', marginBottom: 12 },
    activateText: { fontSize: 14 },
    activateButtonStyle: { paddingHorizontal: 20, paddingVertical: 10 },
    acceptButtonViewStyle: { flexDirection: 'row', justifyContent: 'space-around', paddingVertical: 10 },
    acceptButtonStyle: { alignItems: 'center' },
    imageStyle: { flex: 1 },
    textContainer: { paddingHorizontal: 20, paddingTop: 20 },
    textStyle: { fontSize: 28, fontWeight: '700', color: '#fff' },
    cardStyle: { backgroundColor: '#fff', borderRadius: 16, margin: 20, padding: 20 },
    checkboxContainer: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 12 },
    termsText: { color: '#2d6a4f', textDecorationLine: 'underline' },
    andText: { color: '#666' },
    webViewWrapper: { flex: 1, minHeight: 300 },
    modalView: { margin: 0 },
    closeIconView: { alignSelf: 'flex-end', padding: 10 },
});

export default styles;
