export const MAKE_GENERIC_FEATURE_CONFIG_ACTION = 'MAKE_GENERIC_FEATURE_CONFIG_ACTION';


export const ADDRESS_CONFIG_TYPES = {
    COUNTRY_CONFIG: 'COUNTRY_CONFIG',
    S3_CONFIG_SUCCESS: 'S3_CONFIG_SUCCESS'
}