export const SESSION_MANAGER_TYPES = {
    SESSION_RESET_REFRESH_TOKEN_SUCCESS: 'SESSION_RESET_REFRESH_TOKEN_SUCCESS',
    SET_SESSION_MIGRATED: 'SET_SESSION_MIGRATED',
    REFRESH_ACCESS_TOKEN: 'REFRESH_ACCESS_TOKEN',
    RESET_PUBLIC_TOKEN_ON_MIGRATION: 'RESET_PUBLIC_TOKEN_ON_MIGRATION',
    RESET_SECONDARY_TOKEN: 'RESET_SECONDARY_TOKEN',
    SET_SECONDARY_TAKEAWAY_ACTIVE_STORE: 'SET_SECONDARY_TAKEAWAY_ACTIVE_STORE',
};
